# Generated by Django 5.1.4 on 2026-08-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.FloatField(default=0.0),
        ),
    ]
