# Generated by Django 5.1.4 on 2026-08-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_card_assignee_card_created_by_card_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='board',
            name='last_summary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
